[[models]]
name = "Tanuko"
billboarding = false
enablebreathing = true
scale = 1

[models.position]
x = 0
y = 0
z = 0

[models.rotation]
x = 0
y = 0
z = 0

[models.canvasOffset]
x = 0
y = 0

[global]
allowModeSwitch = true
startupMode = 0